Fix uwsgi SystemError
On serving pdf files, we have the following error:

        SystemError: <built-in function uwsgi_sendfile> returned a
        result with an error set

This happens after the upgrade to python 3.6. Recommended fix found
here:

    https://github.com/unbit/uwsgi/issues/1126